name: Unit- and functional tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Directory permissions for .composer are wrong, so we remove the complete directory
      # https://github.com/actions/virtual-environments/issues/824
      - name: Delete .composer directory
        run: |
          sudo rm -rf ~/.composer

      - name: Validate composer.json
        run: |
          cd .Build
          composer validate

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install composer dependencies
        run: |
          cd .Build
          composer install --no-progress

      - name: Unit tests
        run: |
          echo "Running unit tests";
          .Build/vendor/bin/phpunit -c .Build/phpunit/UnitTests.xml

      - name: Functional tests
        run: |
          export typo3DatabaseName="typo3";
          export typo3DatabaseHost="127.0.0.1";
          export typo3DatabaseUsername="root";
          export typo3DatabasePassword="root";
          echo "Running functional tests";
          find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/vendor/bin/phpunit -c .Build/phpunit/FunctionalTests.xml {}'
